apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/vmmaltsev/devops-portfolio-2025.git'
    targetRevision: main
    path: gitops/apps/postgresql
    helm:
      releaseName: postgresql
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true